# -*- coding: utf-8 -*-
"""NumericalMLE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gBMolDBsnofGHeh3mpIAYd1a_neXoZVF

# Gerekli Kütüphanelerin Yüklenmesi (Bağımlılıklar)
Ödevde kullanılacak matematiksel hesaplamalar, optimizasyon işlemleri ve veri görselleştirme adımları için gerekli temel kütüphaneler.
"""

# Veri manipülasyonu ve matematiksel işlemler için
import numpy as np

# Kayıp fonksiyonunu minimize etmek (sayısal MLE) için
import scipy.optimize as opt

# Teorik PMF dağılımını elde etmek için
from scipy.stats import poisson

# Grafikleri çizdirmek ve görselleştirmek için
import matplotlib.pyplot as plt

"""# Bölüm 1: Python ile Sayısal (Numerical) MLE
Bu bölümde, analitik olarak türevini aldığımız fonksiyonu Python kullanarak "Kayıp Fonksiyonu Minimizasyonu" (Negative Log-Likelihood) yöntemiyle çözecek ve en iyi $\lambda$ (lambda) parametresini tahmin edeceğiz.
"""

import numpy as np
import scipy.optimize as opt
import matplotlib.pyplot as plt

# Gözlemlenen Trafik Verisi (1 dakikada geçen araç sayısı)
traffic_data = np.array([12, 15, 10, 8, 14, 11, 13, 16, 9, 12, 11, 14, 10, 15])

def negative_log_likelihood(lam, data):
    """
    Poisson dağılımı için Negatif Log-Likelihood hesaplar.
    log(k!) terimi sabit olduğu için ihmal edilebilir.
    """
    n = len(data)

    # Scipy minimize fonksiyonu parametreyi genelde bir dizi (array) olarak gönderir.
    # Hata almamak için değerini çıkarıyoruz:
    lam_val = lam[0] if isinstance(lam, np.ndarray) else lam

    # TODO: Log-likelihood formülünü (negatif olarak) buraya yazın
    # Normal Log-Likelihood: -n * lam + log(lam) * sum(k)  (sabit terim atıldı)
    # Negatif hali (NLL): n * lam - log(lam) * sum(k)
    nll = (n * lam_val) - (np.log(lam_val) * np.sum(data))

    return nll

# Başlangıç tahmini
initial_guess = 1.0

# Optimizasyon: NLL'yi minimize etmek, Likelihood'u maximize etmektir.
result = opt.minimize(negative_log_likelihood,
                      initial_guess,
                      args=(traffic_data,),
                      bounds=[(0.001, None)])

print(f"Sayısal Tahmin (MLE lambda): {result.x[0]:.4f}")
print(f"Analitik Tahmin (Ortalama): {np.mean(traffic_data):.4f}")

"""# Bölüm 2: Model Karşılaştırma ve Görselleştirme
Bu bölümde, hesaplanan $\lambda$ parametresi kullanılarak teorik Poisson Olasılık Kütle Fonksiyonu (PMF) ile gerçek trafik verisinin histogramı aynı grafik üzerinde karşılaştırılacaktır.


"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import poisson

# Önceki adımdan elimizde olan veriler ve bulduğumuz lambda değeri
traffic_data = np.array([12, 15, 10, 8, 14, 11, 13, 16, 9, 12, 11, 14, 10, 15])
lambda_mle = np.mean(traffic_data) # Tahmin edilen lambda (Sayısal ile aynıydı: 12.14)

# Grafik boyutunu ayarlama
plt.figure(figsize=(10, 6))

# 1. Gerçek verinin histogramını çizme
# (density=True parametresi ile y eksenini frekans yerine olasılığa çeviriyoruz ki PMF ile uyumlu olsun)
min_val = np.min(traffic_data)
max_val = np.max(traffic_data)
# Çubukların tam sayıların üzerine düzgün oturması için bin ayarı
bins = np.arange(min_val - 0.5, max_val + 1.5, 1)

plt.hist(traffic_data, bins=bins, density=True, alpha=0.6, color='skyblue',
         edgecolor='black', label='Gerçek Veri Histogramı')

# 2. Poisson PMF (Olasılık Kütle Fonksiyonu) çizimi
# X ekseni değerlerini oluşturalım
x = np.arange(min_val - 2, max_val + 3)
pmf_values = poisson.pmf(x, lambda_mle)

# PMF'i kesikli (discrete) bir dağılım olduğu için nokta ve dikey çizgilerle gösterelim
plt.plot(x, pmf_values, 'ro-', ms=6, label=f'Poisson PMF Model (λ = {lambda_mle:.2f})')
plt.vlines(x, 0, pmf_values, colors='r', lw=2, alpha=0.5)

# Grafik süslemeleri ve isimlendirmeler
plt.title('Gerçek Trafik Verisi vs. Tahmin Edilen Poisson Modeli', fontsize=14)
plt.xlabel('1 Dakikada Geçen Araç Sayısı (k)', fontsize=12)
plt.ylabel('Olasılık P(k)', fontsize=12)
plt.xticks(x)
plt.legend()
plt.grid(axis='y', alpha=0.75, linestyle='--')

# Grafiği ekrana bas
plt.show()