# -*- coding: utf-8 -*-
"""Colab'e hoş geldiniz.

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

!pip install hmmlearn

from hmmlearn import hmm
import numpy as np

#EV kelimesi için hmm modeli
model_ev = hmm.CategoricalHMM(n_components=2)
model_ev.startprob_ = np.array([1.0, 0.0])
model_ev.transmat_ = np.array([[0.7, 0.3],
                               [0.0, 1.0]])
model_ev.emissionprob_ = np.array([[0.8, 0.1, 0.1],
                                   [0.1, 0.8, 0.1]])

#OKUL kelimesi için hmm modeli
model_okul = hmm.CategoricalHMM(n_components=2)
model_okul.startprob_ = np.array([1.0, 0.0])
model_okul.transmat_ = np.array([[0.5, 0.5],
                                 [0.0, 1.0]])
model_okul.emissionprob_ = np.array([[0.1, 0.2, 0.7],
                                     [0.1, 0.1, 0.8]])

#Log-Likelihood hesaplayan ve sınıflandırma yapan fonksiyon
def kelime_siniflandirici(test_verisi):
    score_ev = model_ev.score(test_verisi)
    score_okul = model_okul.score(test_verisi)

    print(f"EV modeli Log-Likelihood puanı: {score_ev:.4f}")
    print(f"OKUL modeli Log-Likelihood puanı: {score_okul:.4f}")

    if score_ev > score_okul:
        return "Bu kelime büyük ihtimalle EV"
    elif score_okul > score_ev:
        return "Bu kelime büyük ihtimalle OKUL"
    else:
        return "Olasılıklar eşit"

#Temsili test verileri ile fonksiyonu deneme
test_data_1 = np.array([[0, 1, 1]]).T
test_data_2 = np.array([[2, 2, 2]]).T

print(" 1. Test Verisi (Beklenti: EV)")
print(kelime_siniflandirici(test_data_1))

print("\n 2. Test Verisi (Beklenti: OKUL)")
print(kelime_siniflandirici(test_data_2))